<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- The 'action' attribute of this form specifies that the form data will be submitted to the same PHP script that generated by the page  -->
    <form action="" method="post">
    <!-- Create a Table To Show the Gatespace of the WEbsite -->
    <Table>
        <tr>
            <th>Grade Distribution Graph
                <Table>
                    <tr>
                        <td><label for="grade_A">How many is A: </label></td>
                        <td><input type="text" name="grade_A" id="grade_A"> </td>
                    </tr>
                    <tr>
                        <td><label for="grade_B">How many is B: </label></td>
                        <td><input type="text" name="grade_B" id="grade_B"></td>
                    </tr>
                    <tr>
                        <td><label for="grade_C">How many is C: </label></td>
                        <td><input type="text" name="grade_C" id="grade_C"></td>
                    </tr>
                    <tr>
                        <td><label for="grade_D">How many is D: </label></td>
                        <td><input type="text" name="grade_D" id="grade_D"></td>
                    </tr>
                    <tr>
                        <td><label for="grade_F">How many is F: </label></td>
                        <td><input type="text" name="grade_F" id="grade_F"></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td align="left"><input type="submit"  name ="submit_login" value="Graph Grade Distribution"></td>
                    </tr>
                </Table>
            </th>

        </tr>
    </Table>
    </form>

<?php
    // Display error if True
    ini_set("display_errors", 1);

    // Check if the Form had been submitted
    if (isset($_POST['submit_login'])){
    
    // Get the Input Values of the Letter Grades
        $numA = $_POST['grade_A'];
        $numB = $_POST['grade_B'];
        $numC = $_POST['grade_C'];
        $numD = $_POST['grade_D'];
        $numF = $_POST['grade_F'];

    // Get the Total Grades
    $total_Grades = $numA + $numB + $numC + $numD + $numF;

    // Calculate the Percentage of each Letter
			$percent_A = round(($numA / $total_Grades) * 100);
			$percent_B = round(($numB / $total_Grades) * 100);
			$percent_C = round(($numC / $total_Grades) * 100);
			$percent_D = round(($numD / $total_Grades) * 100);
			$percent_F = round(($numF / $total_Grades) * 100);
    
    // // Create a Table for the Total Amount of the Grades and each Amount of Different Grade
        if (!empty($num_A) && !empty($num_B) && !empty($num_C) && !empty($num_D) && !empty($num_F)){
            echo 'success';
        } else { 
            echo 'bilat ni mama';
        }
        
    }   

?>
</body>
</html>